In [1]:
from __future__ import division
import pickle
import re
import os, os.path
import pandas as pd
import pickle
import sys
from sklearn.cross_validation import train_test_split
from sklearn.metrics import log_loss, confusion_matrix
import io

In [2]:
#output_path='dict_full' #where to store the output
label_csv_path='../trainLabels.csv' #path to csv file mapping filenames to labels
data_path = '../train/' #path to the data

dump_path = '../new_opcodes.txt'
unpickled_file=open(dump_path,'rb')
unpickled_dict=pickle.load(unpickled_file)
raw_opcode_list=unpickled_dict.keys() #list of opcodes to filter
#raw_opcode_list=['mov','add','sub','imul'] #list of opcodes to filter

In [3]:
opcode_dict_l=list()
for i in range(0,9):
    opcode_dict=dict()
    for item in raw_opcode_list:
        formatted_opcode=' '+item+' '
        opcode_dict[formatted_opcode]=0
    opcode_dict_l.append(opcode_dict)

def count_opcodes(directory_path,filename):
    #byte_limit=100
    new_opcode_dict=dict()
    # print opcode_dict
    for key in opcode_dict.keys():
        new_opcode_dict[key] = 0
    try:
        path=directory_path+filename
        openfile = io.open(path,'r',encoding='latin-1')
        #openfile = open(path,'rb')
        l_lines=openfile.readlines()
        count=0
        lc=0
        for line in l_lines:
            #print ("line found")
            opcode_group = re.search('\s\s\s[a-z][a-z]+\s\s\s',line)
            if opcode_group:
                opcode = opcode_group.group()
                opcode = opcode.strip()
                opcode=' '+opcode+' '
                if opcode in new_opcode_dict.keys():
                    #print ("key found")
                    new_opcode_dict[opcode] += 1
                
        openfile.close()
    except IOError:
        print ("Could not open file!")
    total=1
    '''
    for opcode in new_opcode_dict.keys():
        total+=new_opcode_dict[opcode]
    # print (new_opcode_dict)
    for opcode in new_opcode_dict.keys():
        new_opcode_dict[opcode] = new_opcode_dict[opcode]/total
    #print new_opcode_dict
    '''
    return new_opcode_dict

In [12]:
from sklearn.cross_validation import cross_val_score, KFold
from sklearn.linear_model import LogisticRegression

import numpy as np
import os.path

dt = np.dtype([('Id', 'a30'), ('Class', 'u2')])
data = np.loadtxt(label_csv_path, skiprows=1, delimiter = ',', dtype=dt)

X = np.zeros((data.shape[0], len(raw_opcode_list)))
Y = data['Class']

for i, (Id, Class) in enumerate(data):
    #print "iterating"
    asmFile = Id[1:-1]+'.asm'
    countDict = count_opcodes(data_path,asmFile)
    j = 0
    for key in countDict.keys():
        #print countDict[key]
        X[i][j] = countDict[key]
        j = j + 1
    if i%100 == 0:
        print i, "I am alive"


0 I am alive
100 I am alive
200 I am alive
300 I am alive
400 I am alive
500 I am alive
600 I am alive
700 I am alive
800 I am alive
900 I am alive
1000 I am alive
1100 I am alive
1200 I am alive
1300 I am alive
1400 I am alive
1500 I am alive
1600 I am alive
1700 I am alive
1800 I am alive
1900 I am alive
2000 I am alive
2100 I am alive
2200 I am alive
2300 I am alive
2400 I am alive
2500 I am alive
2600 I am alive
2700 I am alive
2800 I am alive
2900 I am alive
3000 I am alive
3100 I am alive
3200 I am alive
3300 I am alive
3400 I am alive
3500 I am alive
3600 I am alive
3700 I am alive
3800 I am alive
3900 I am alive
4000 I am alive
4100 I am alive
4200 I am alive
4300 I am alive
4400 I am alive
4500 I am alive
4600 I am alive
4700 I am alive
4800 I am alive
4900 I am alive
5000 I am alive
5100 I am alive
5200 I am alive
5300 I am alive
5400 I am alive
5500 I am alive
5600 I am alive
5700 I am alive
5800 I am alive
5900 I am alive
6000 I am alive
6100 I am alive
6200 I am alive
6300

In [ ]:
label_csv_path='../trainLabels.csv' #path to csv file mapping filenames to labels
data_path = '../train/' #path to the data

opcode_dict_l=list()

for i in range(0,9):
    opcode_dict=dict()
    for item in raw_opcode_list:
        formatted_opcode=' '+item+' '
        opcode_dict[formatted_opcode]=0
    opcode_dict_l.append(opcode_dict)

def count_opcodes(directory_path,filename):
    #byte_limit=100
    new_opcode_dict=dict()
    # print opcode_dict
    for key in opcode_dict.keys():
        new_opcode_dict[key] = 0
    try:
        path=directory_path+filename
        openfile = io.open(path,'r',encoding='latin-1')
        #openfile = open(path,'rb')
        l_lines=openfile.readlines()
        count=0
        lc=0
        for line in l_lines:
            #print ("line found")
            opcode_group = re.search('\s\s\s[a-z][a-z]+\s\s\s',line)
            if opcode_group:
                opcode = opcode_group.group()
                opcode = opcode.strip()
                opcode=' '+opcode+' '
                if opcode in new_opcode_dict.keys():
                    #print ("key found")
                    new_opcode_dict[opcode] += 1
                
        openfile.close()
    except IOError:
        print ("Could not open file!")
    total=1
    '''
    for opcode in new_opcode_dict.keys():
        total+=new_opcode_dict[opcode]
    # print (new_opcode_dict)
    for opcode in new_opcode_dict.keys():
        new_opcode_dict[opcode] = new_opcode_dict[opcode]/total
    #print new_opcode_dict
    '''
    return new_opcode_dict

In [32]:
for i, j in enumerate(Id_list):
    print i,j

0 VAd3PcXhWpDw0msoLTru
1 OWEz8fJgXyQehS9Ui4rN
2 zd4ZGDFm3ihRYP5SjkO1
3 lv2VeW1qsi04FUBaSyIp
4 WOSIobrKq7V8tj0ym6Aw
5 uFQfdlM3UGsptgaPDbkH
6 TNw3kAylcbgrePnHEDdq
7 Wd9opi2mxq0rvJPHyTZG
8 u7YImg0jUJvNCwptlDhW
9 SN4QKTdXEoCML13yvaeB
10 RB86EFgaNxPvt92imZ7Q
11 r5C4UmePI1G7EFBOpfwd
12 nCihxJXzwKmVaOsMLuFE
13 YvtPighXu2kILcnowB4y
14 yWnDl7EzLrtZe54xuSCF
15 SyKkFEn6V8QjuIiLp4T1
16 qbZs3inKkfATXytr8oPR
17 Q1LhkmwfGHsPUd3gOZR5
18 sHt1Edq2Gmu5rAKclZLS
19 l1pC4o6PRzLuigEAGkwb
20 YSZvlEnyKRLk1eaQTsdb
21 Q58fV4MGC367oFOkNHEP
22 tqJPYDehEUzXZHjTWQS5
23 NQ4yu0CitVRaWqZG6nwY
24 Y5CQSHq2MDG9ucFK1jUL
25 qmdot5FiOrL8HAs2NKgU
26 vTEB0kSK7acRXqAInibr
27 o3fjCMq2hBOElV6NPwGT
28 OGaX5ryeEC1IhJF3gqpn
29 VPjNuxgy31XdULcSR70l
30 vueKiswPFordp42NklLQ
31 MlAwbugZS9v3Gjd0xWzR
32 SF4TE7ZLlzpWBweRdnAy
33 Xfjuh9dsBVm6QPZA5Dry
34 l3jCozvgu5NEWR0hBOJm
35 KUwiIgcYGFRtq91M48CQ
36 OkD6yo1jwQJmKzYbIMGi
37 R0tFikXuYWjEhvg5rUTs
38 yV0XgJcPZmtiEWahL8sH
39 qKVLb0m9UsH7IcvNA2gD
40 z9ILBVnE1f5F3w4kbem7
41 tWAYC5m3calwu2dfhe1j
42

In [ ]:
data_path = '../test/'
list_files = [ f for f in listdir(mypath) if isfile(join(mypath,f)) ]
set_files = set([ os.path.splitext(el)[0] for el in list_files ])
 
Id_list = list(set_files) 
 
#X_test = np.zeros(( len(set_files), 2 ))

X_test = np.zeros((len(set_files), len(raw_opcode_list)))

for i, Id in enumerate(Id_list):
    #print "iterating"
    asmFile = Id+'.asm'
    countDict = count_opcodes(data_path,asmFile)
    j = 0
    for key in countDict.keys():
        #print countDict[key]
        X_test[i][j] = countDict[key]
        j = j + 1
    if i%100 == 0:
        print i, "I am alive"

In [41]:
X.shape

(10868, 146)

In [39]:
X[100]

array([  1.67100000e+03,   0.00000000e+00,   2.62000000e+02,
         0.00000000e+00,   2.60000000e+01,   9.00000000e+01,
         0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,   1.30000000e+01,   0.00000000e+00,
         2.20000000e+01,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         6.31000000e+02,   9.30000000e+01,   0.00000000e+00,
         1.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         2.70000000e+01,   4.30000000e+01,   0.00000000e+00,
         0.00000000e+00,   2.00000000e+00,   0.00000000e+00,
         2.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,   4.30000000e+01,   0.00000000e+00,
         1.00000000e+00,   1.00000000e+00,   0.00000000e+00,
         3.33100000e+03,

In [16]:
Y

array([1, 1, 1, ..., 9, 9, 9], dtype=uint16)

In [93]:
def run_cv(X,y, clf):
 
    # Construct a kfolds object
    kf = KFold(len(y),n_folds=20,shuffle=True)
    y_prob = np.zeros((len(y),9))
    y_pred = np.zeros(len(y))
     
    # Iterate through folds
    for train_index, test_index in kf:
        X_train, X_test = X[train_index], X[test_index]
        y_train = y[train_index]
 
        clf.fit(X_train,y_train)
        y_prob[test_index] = clf.predict_proba(X_test)
        y_pred[test_index] = clf.predict(X_test)
     
    return y_prob, y_pred

In [19]:
#clf1 = ExtraTreesClassifier(n_estimators=2000, max_features=None, min_samples_leaf=1,
        #min_samples_split=9, n_jobs=1, criterion='gini')
#p2, pred2 = run_cv(X,Y,clf1)
#print &quot;%.3f&quot; % log_loss(Y, p2)
#cm = confusion_matrix(Y, pred2)
#print(cm)
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier
 
#print &quot;Extra Tree:&quot;
clf2 = ExtraTreesClassifier(n_estimators=2000, max_features=None, min_samples_leaf=2,
        min_samples_split=3, n_jobs=1, criterion='gini')
p3, pred3 = run_cv(X,Y,clf2)
#print &quot;%.3f&quot; % log_loss(Y, p3)
cm = confusion_matrix(Y, pred3)
print(cm)
 
print 'Combination:',
#p6 = (p2 + p3) / 2.
#print &quot;%.3f&quot; % log_loss(Y, p6)
 
'''
clf = ExtraTreesClassifier(n_estimators=2000, max_features=None, min_samples_leaf=1,
        min_samples_split=9, n_jobs=2, criterion='gini')
clf = ExtraTreesClassifier(n_estimators=2000, max_features=None, min_samples_leaf=2,
        min_samples_split=3, n_jobs=2, criterion='gini') 
Extra Tree: 0.251
[[1353   35    0    4   10   53    6   56   24]
 [  58 2377    0    6    1   25    2    4    5]
 [   0    5 2937    0    0    0    0    0    0]
 [   5   13    0  447    0    5    0    3    2]
 [  18    2    0    0   17    4    0    1    0]
 [  60   19    1    8    2  639    0   20    2]
 [   4    5    0    0    0    0  389    0    0]
 [  94   12    3    7    1   28    2 1076    5]
 [  26    8    0    3    1    5    0    3  967]]
Extra Tree: 0.218
[[1341   42    0    4    9   51    7   64   23]
 [  49 2372    0    8    2   32    2    7    6]
 [   0    4 2937    0    0    1    0    0    0]
 [   5   11    0  448    0    5    0    4    2]
 [  21    4    1    0   13    1    0    2    0]
 [  57   24    2    9    0  634    0   21    4]
 [   2   10    0    0    0    0  386    0    0]
 [  81   17    4    7    0   28    2 1083    6]
 [  25    5    0    3    1    6    0    3  970]]
'''
 
##################
# Get prediction #
##################
 
#clf1.fit(X, Y)
#result1 = clf1.predict_proba(X_test)


[[1523    2    2   10    0    0    0    4    0]
 [   5 2464    0    8    0    1    0    0    0]
 [   0    0 2937    5    0    0    0    0    0]
 [   1    0    1  473    0    0    0    0    0]
 [   3    0    0    6   32    0    0    1    0]
 [   6    0    0   24    0  719    0    0    2]
 [   0    0    0   11    0    0  387    0    0]
 [  35    0    0   16    0    3    0 1174    0]
 [   1    0    0    1    0    2    0    3 1006]]
Combination:

NameError: name 'X_test' is not defined

In [176]:
sum = 0
for i in range(len(cm)):
    sum = sum + cm[i][0]
    print sum

1523
1528
1528
1529
1532
1538
1538
1573
1574


In [ ]:
1574

In [23]:
print '%.3f' % log_loss(Y, p3)

0.065


In [28]:
from os import listdir
from os.path import isfile, join

mypath = '../test'
list_files = [ f for f in listdir(mypath) if isfile(join(mypath,f)) ]
set_files = set([ os.path.splitext(el)[0] for el in list_files ])
 
Id_list = list(set_files) 
 
X_test = np.zeros(( len(set_files), 2 ))
 
print X_test.shape
 
for i, Id in enumerate(Id_list):
    X_test[i][0] = os.path.getsize('../test/'+Id+'.asm')
    X_test[i][1] = os.path.getsize('../test/'+Id+'.bytes')

(10873, 2)


In [ ]:
clf2.fit(X, Y)

In [43]:
result2 = clf2.predict_proba(X_test)
 
#result = (result1 + result2) / 2.0

#print '%.3f' % log_loss(Y, p2)
print '%.3f' % log_loss(Y, p3)
#print '%.3f' % log_loss(Y, p6)
 
w = open('freq_all_features.csv', 'w')
w.write('&quot;Id&quot;,&quot;Prediction1&quot;,&quot;Prediction2&quot;,&quot;Prediction3&quot;,&quot;Prediction4&quot;,')
w.write('&quot;Prediction5&quot;,&quot;Prediction6&quot;,&quot;Prediction7&quot;,&quot;Prediction8&quot;,&quot;Prediction9&quot;\n')
         
assert(len(set_files) == X_test.shape[0])
 
for i, sample in enumerate(result2):
    string = '&quot;%s&quot;,%s\n' %(Id_list[i], ','.join(map(str, sample)) )
    w.write(string)
    
w.close()

0.065


In [53]:
import os
os.system("echo hi")

0

In [42]:
import pickle
file_Name = "all_features_test"
# open the file for writing
fileObject = open(file_Name,'wb')
pickle.dump(X_test,fileObject)
fileObject.close()

In [34]:
X_bk = X
fileObject = open("all_features",'r')
X_new = pickle.load(fileObject)

In [36]:
X_new==X

array([[ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       ..., 
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True]], dtype=bool)

In [30]:
file_Name = "extra_trees_clf2_all_features_fit"
# open the file for writing
fileObject = open(file_Name,'wb')
pickle.dump(clf2,fileObject)
fileObject.close()

#read clf2 and do clf2.fit(X,Y) and predict

In [ ]:
# we open the file for reading
#fileObject = open(file_Name,'r')  
# load the object from the file into var b
#b = pickle.load(fileObject)

In [28]:
result_ll = list()
def trainCV(X,y, clf):
 
    # Construct a kfolds object
    kf = KFold(len(y),n_folds=3,shuffle=True)
    #y_prob = np.zeros((len(y),3))
    y_pred = np.zeros(len(y))

    avLoss = 0
     
    # Iterate through folds
    for train_index, test_index in kf:
        X_train, X_test = X[train_index], X[test_index]
        #print X_train
        #print "test", test_index
        y_train = y[train_index]
 
        clf.fit(X_train,y_train)
    #print clf.get_params()
    print clf.coef_, clf.intercept_
    predictions = clf.predict_proba(X_test)
    #print "predictions", predictions
    #y_prob[test_index] = predictions
    y_pred[test_index] = clf.predict(X_test)
    y_test = y[test_index]
    #print type(y_test), type(y_pred[test_index])
    logLoss = log_loss(y_test, predictions)
    print 'Log loss is %.3f' % logLoss
    avLoss = avLoss + logLoss
    avLoss = avLoss/len(kf)
    print 'Average Log Loss is %.3f' %avLoss
    result_ll.append(avLoss)
    return avLoss

In [16]:
cList = [1e3,1e2,10,1,0.1,0.01,0.001]
minError = 100
minC = cList[0]
for cVal in cList:
    clf = LogisticRegression(C=cVal)
    error = trainCV(X,Y,clf)
    print 'current Log loss is %.3f' % error
    print 'current C is %.3f' % cVal
    if error < minError:
        minError = error
        minC = cVal
print 'Min log loss is %.3f' % minError
print 'Min C is %.3f' % minC

[[ -1.96617097e-03   1.98084991e-03  -2.96728929e-03 ...,  -2.64408564e-02
   -3.44254398e-03   3.98942019e-02]
 [ -1.00175949e-02  -8.32268239e-11   7.29817094e-03 ...,  -5.54010658e-03
   -8.30846754e-04   7.32758282e-07]
 [  1.03631888e-01  -3.09518003e-11  -1.52191535e-01 ...,   8.12100336e-02
   -7.89844124e-07  -4.10567528e-08]
 ..., 
 [  2.36587670e-02  -2.92980683e-11  -2.50278783e-01 ...,  -2.85661677e-01
   -3.96147264e-02  -3.24182081e-03]
 [ -4.85451452e-03  -4.02982570e-03   8.16675981e-03 ...,   1.47488011e-02
   -1.84045908e-03  -8.07502727e-02]
 [  1.27966127e-02  -4.03221174e-10   3.69355474e-02 ...,  -2.55663689e-02
   -5.77728684e-03  -3.61980939e-02]] [-1.14312357 -1.70164837 -0.01596233 -0.13835864 -1.37896058 -1.25589562
 -0.24752163 -2.10655474 -1.63023021]
Log loss is 0.276
Average Log Loss is 0.092
current Log loss is 0.092
current C is 1000.000
[[ -2.38162027e-03   1.35035001e-02  -4.72544656e-04 ...,  -2.51983102e-02
   -4.75615091e-03   2.93527033e-01]
 [ -1

In [18]:
result_logistic = result_ll

In [24]:
from sklearn.datasets import make_moons, make_circles, make_classification
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.lda import LDA
from sklearn.qda import QDA

In [ ]:
cList = [1e3,1e2,10,1,0.1,0.01,0.001]
minError = 100
minC = cList[0]
for cVal in cList:
    clf = SVC(gamma=2, C=cVal, probability=True)
    error = trainCV(X,Y,clf)
    print 'current Log loss is %.3f' % error
    print 'current C is %.3f' % cVal
    if error < minError:
        minError = error
        minC = cVal
print 'Min log loss is %.3f' % minError
print 'Min C is %.3f' % minC
result_svc = result_ll

In [21]:
s = " dfd "
s= s.strip()
s

'dfd'

In [ ]:
classifiers = [
    KNeighborsClassifier(20),
    #SVC(kernel="linear", C=0.025, probability=True),
    #SVC(gamma=2, C=1, probability=True),
    DecisionTreeClassifier(max_depth=5),
    RandomForestClassifier(max_depth=10, n_estimators=100, max_features=2)]
    #AdaBoostClassifier(),
    #GaussianNB(),
    #LDA()]

In [23]:
result_logistic

[0.091992739968820444,
 0.12064382699750718,
 0.12506234603348257,
 0.12709946783554885,
 0.10259073333381809,
 0.10332257811087779,
 0.1377894873682288]

In [58]:
import numpy as np
importances = clf2.feature_importances_
std = np.std([tree.feature_importances_ for tree in clf2.estimators_],
             axis=0)
indices = np.argsort(importances)[::-1]

# Print the feature ranking
print("Feature ranking:")

for f in range(100):
    print("%d. feature %d (%f)" % (f + 1, indices[f], importances[indices[f]]))

Feature ranking:
1. feature 37 (0.069468)
2. feature 70 (0.043361)
3. feature 24 (0.037471)
4. feature 143 (0.036377)
5. feature 107 (0.035568)
6. feature 5 (0.034863)
7. feature 93 (0.032694)
8. feature 129 (0.029373)
9. feature 139 (0.029330)
10. feature 97 (0.029011)
11. feature 78 (0.028726)
12. feature 121 (0.027827)
13. feature 31 (0.027561)
14. feature 0 (0.025143)
15. feature 92 (0.024878)
16. feature 133 (0.024801)
17. feature 79 (0.024263)
18. feature 52 (0.021614)
19. feature 54 (0.020529)
20. feature 53 (0.019412)
21. feature 48 (0.018102)
22. feature 2 (0.017625)
23. feature 25 (0.017169)
24. feature 34 (0.016331)
25. feature 43 (0.016142)
26. feature 51 (0.015224)
27. feature 109 (0.015056)
28. feature 114 (0.014441)
29. feature 108 (0.013460)
30. feature 120 (0.013457)
31. feature 98 (0.012881)
32. feature 123 (0.011774)
33. feature 16 (0.011564)
34. feature 62 (0.011153)
35. feature 50 (0.011119)
36. feature 46 (0.010874)
37. feature 10 (0.010102)
38. feature 66 (0.0094

In [68]:
impIndices = indices[:50]
impIndices

array([ 37,  70,  24, 143, 107,   5,  93, 129, 139,  97,  78, 121,  31,
         0,  92, 133,  79,  52,  54,  53,  48,   2,  25,  34,  43,  51,
       109, 114, 108, 120,  98, 123,  16,  62,  50,  46,  10,  66,  19,
        84,  30,  60,  12,   4,  36, 131,  88, 112, 136,  75,  85, 105,
        28, 126,  44, 102,  94,  27,  26, 125, 111,  63,  59, 113,   3,
        76, 124,  57,  42, 116,  82, 101, 142,  32,  14,  45,  20, 103,
       118, 100, 106,  95,   6, 130,  73, 104, 115,  11,  15,  89,  47,
        68,  81,  69, 119,  39, 128, 127,  22,  33])

In [86]:
impIndices = indices[:50]
impTrainFeatures = []
for i in range(len(X)):
    impItems = [X[i][j] for j in impIndices]
    impTrainFeatures.append(impItems)

In [87]:
impTestFeatures = []
for i in range(len(X_test)):
    impItems = [X_test[i][j] for j in impIndices]
    impTestFeatures.append(impItems)

In [88]:
clf3 = LogisticRegression(C=0.025)
p4, pred4 = run_cv(impTrainFeatures,Y,clf3)
#print &quot;%.3f&quot; % log_loss(Y, p3)
cm = confusion_matrix(Y, pred4)
print(cm)
 
print 'Combination:',
#p6 = (p2 + p3) / 2.
print '%.3f&' % log_loss(Y, p4)

TypeError: only integer arrays with one element can be converted to an index

In [124]:
clf3 = LogisticRegression(C=1)
# Construct a kfolds object
X = impTrainFeatures
y=Y
#X = impTrainFeatures
kf = KFold(len(y),n_folds=10,shuffle=True)
y_prob = np.zeros((len(y),9))
y_pred = np.zeros(len(y))

# Iterate through folds
for train_index, test_index in kf:
    #print train_index, test_index
    #X_train, X_test = X[train_index], X[test_index]
    X_train = [X[i] for i in train_index]
    X_test = [X[i] for i in test_index]
    #y_train = y[train_index]
    y_train = [y[i] for i in train_index]

    clf3.fit(X_train,y_train)
    y_prob[test_index] = clf3.predict_proba(X_test)
    y_pred[test_index] = clf3.predict(X_test)
    print '%.3f' % log_loss(Y, y_prob)
    #break

#return y_prob, y_pred

2.008


In [102]:
clf3

LogisticRegression(C=0.025, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, penalty='l2', random_state=None, tol=0.0001)

In [112]:
f = open('../syscount.txt', 'r')
sysCountTrain = []
for line in f:
    sysCountTrain.append(int(line.split(":")[1][:-1]))

In [123]:
clf3 = LogisticRegression(C=1)
# Construct a kfolds object
y=Y
#X = impTrainFeatures
kf = KFold(len(y),n_folds=10,shuffle=True)
y_prob = np.zeros((len(y),9))
y_pred = np.zeros(len(y))

# Iterate through folds
for train_index, test_index in kf:
    #print train_index, test_index
    #X_train, X_test = X[train_index], X[test_index]
    X_train = [[sysCountTrain[i]] for i in train_index]
    #print len(X_train)
    X_test = [[sysCountTrain[i]] for i in test_index]
    #y_train = y[train_index]
    y_train = [y[i] for i in train_index]
    #print len(y_train)

    clf3.fit(X_train,y_train)
    
    y_prob[test_index] = clf3.predict_proba(X_test)
    y_pred[test_index] = clf3.predict(X_test)
    print '%.3f' % log_loss(Y, y_prob)
    #break

2.168
2.140
2.109
2.080
2.050
2.020
1.989
1.959
1.929
1.901


In [149]:
ensembFeat = []
for feat1,feat2 in zip(impTrainFeatures,sysCountTrain):
    feat1Copy = feat1[:]
    feat1Copy.extend([feat2])    
    ensembFeat.append(feat1Copy)
    #print ensembFeat
    #break

In [150]:
len(impTrainFeatures[0])

50

In [165]:
clf32 = LogisticRegression(C=1)
# Construct a kfolds object
X2 = impTrainFeatures
y2=Y
#X = impTrainFeatures
kf2 = KFold(len(y2),n_folds=10,shuffle=True)
y_prob2 = np.zeros((len(y2),9))
y_pred2 = np.zeros(len(y2))

# Iterate through folds
for train_index2, test_index2 in kf2:
    #print train_index, test_index
    #X_train, X_test = X[train_index], X[test_index]
    X_train2 = [X2[i] for i in train_index2]
    X_test2 = [X2[i] for i in test_index2]
    #y_train = y[train_index]
    y_train2 = [y2[i] for i in train_index2]

    clf32.fit(X_train2,y_train2)
    y_prob[test_index] = clf3.predict_proba(X_test2)
    y_pred[test_index] = clf3.predict(X_test2)
    print '%.3f' % log_loss(y2, y_prob2)
    #break

#return y_prob, y_pred

ValueError: setting an array element with a sequence.

In [156]:
train_index = [0,3,5,6,9,10]
X_train = [X[i] for i in train_index]

In [157]:
X_train

[[0.0,
  15.0,
  11.0,
  5.0,
  13.0,
  1.0,
  0.0,
  0.0,
  89.0,
  19.0,
  36.0,
  14.0,
  1.0,
  53.0,
  0.0,
  12.0,
  11.0,
  5.0,
  6.0,
  1.0,
  81.0,
  6.0,
  3.0,
  0.0,
  1.0,
  0.0,
  7.0,
  0.0,
  0.0,
  0.0,
  0.0,
  1.0,
  0.0,
  1.0,
  18.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  2.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  285],
 [12.0,
  7083.0,
  4234.0,
  1240.0,
  6228.0,
  422.0,
  328.0,
  260.0,
  32566.0,
  6384.0,
  5819.0,
  5052.0,
  249.0,
  10686.0,
  865.0,
  4605.0,
  1214.0,
  194.0,
  849.0,
  267.0,
  28620.0,
  1815.0,
  647.0,
  2.0,
  156.0,
  3.0,
  1723.0,
  36.0,
  66.0,
  9.0,
  47.0,
  228.0,
  0.0,
  203.0,
  2902.0,
  5.0,
  4.0,
  375.0,
  1.0,
  88.0,
  267.0,
  24.0,
  219.0,
  22.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  39.0,
  14,
  14,
  14],
 [2.0,
  561.0,
  463.0,
  175.0,
  527.0,
  25.0,
  85.0,
  25.0,
  5174.0,
  1370.0,
  1139.0,
  661.0,
  49.0,
  1957.0,
  81.0,
  443.0,
  216.0,
  13.0,
  26.0,
  31.0,
 